apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-backup
  namespace: demo-app
spec:
  schedule: "0 2 * * *"           # Tous les jours à 2h du matin
  timeZone: "Europe/Paris"         # Fuseau horaire explicite
  successfulJobsHistoryLimit: 3    # Garde les 3 derniers Jobs réussis
  failedJobsHistoryLimit: 1        # Garde le dernier Job échoué
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:16@sha256:f1c3376c26f2609ab9f29f71f824103fe2fcd8ee0346485cb6122a4f93df6f94
            command: ["pg_dump", "-h", "db-host", "-U", "admin", "mydb"]
          restartPolicy: Never
