apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo-app
  annotations:
    kubernetes.io/change-cause: "Passage nginx 1.31 - patch correctif"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # combien de Pods en surplus
      maxUnavailable: 1 # combien de Pods indisponible
  revisionHistoryLimit: 5 # limiter l'historique des révisions
  progressDeadlineSeconds: 600
  minReadySeconds: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.31@sha256:abe47724e466aeab9a345d8e46a221c2fa8953c7848bb4a3bd9976a7199f8cf2 # anciennement 1.28
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          ports:
            - containerPort: 80
          # injecter TOUS les variables d'environnement
          envFrom:
            - configMapRef:
                name: app-settings
          # injecter les Secrets avec envFrom
            - secretRef:
                name: db-credentials
          # Monter un Secret en volume
          volumeMounts:
          - name: secret-volume
            mountPath: /etc/secrets
            readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: db-credentials
          items:
          - key: environnment
            path: db-env  


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo-app
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP